### ISSUE TITLE
请问运行main.py后dqn为什么并没有表现出收敛呢？

### ISSUE THREAD

**Issue by abcdefghiomn** [Lizonghang/sfc-dqn#1]
得到qoe和error图像中dqn曲线呈现范围内不断上下波动，并不能看出明显的趋于最优的曲线走向。

**Comment by Lizonghang** [comment]
强化学习的曲线经常表现出剧烈的收敛震荡，这是普遍现象，需要长时间运行，然后平滑曲线看总体趋势。

如果超参（如学习率，探索率）设置不当，或奖赏函数设置不当，或任务类型、环境不合适，强化学习也表现不出较好的效果。

**Comment by abcdefghiomn** [comment]
学长好，再次打扰，我看您的画图plot代码中已经进行了smooth平滑处理，而且您跑250个epoch的结果已经呈现出明显收敛趋势，并且曲线很平滑，但我使用相同的画图代码进行画图时，epoch=250时画出的图还是非常震荡，收敛不明显，请问这是代表我需要进一步加大平滑处理的程度吗？而且，如果延长运行时间，在大概350轮后貌似会出现过拟合的情况，导致性能急剧地下降。期待您的解答。
![Figure_1](https://github.com/Lizonghang/sfc-dqn/assets/161568784/45749ec4-102f-42e9-8650-2032a00ce0eb)

**Comment by Lizonghang** [comment]
强化学习的震荡和随机性比较强，有时确实会出现训练久了后性能突然恶化且无法挽回的情况。可以尝试减小学习率，再观察后续的曲线变化。

**Comment by abcdefghiomn** [comment]
好的学长，我再加以尝试，感谢您的解答，麻烦您了。

**Comment by Lizonghang** [comment]
如果你是在学习强化学习，或希望把DQN等强化学习算法应用到你自己的环境中，建议尝试强化学习的开源框架，如Tianshou：

https://github.com/thu-ml/tianshou

这些框架算法、功能完整，非常适合用来尝试、比较不同强化学习算法在某个环境中的表现。

**Comment by abcdefghiomn** [comment]
谢谢！
